set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets Q_OBUF]
set_property -dict {PACKAGE_PIN J4 IOSTANDARD LVCMOS18} [get_ports D]
set_property -dict {PACKAGE_PIN L3 IOSTANDARD LVCMOS18} [get_ports CLK]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS18} [get_ports Q]
set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVCMOS18} [get_ports NOTQ]
