set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets CLK_IBUF]
set_property -dict {PACKAGE_PIN F21 IOSTANDARD LVCMOS18} [get_ports CLK]
set_property -dict {PACKAGE_PIN J4 IOSTANDARD LVCMOS18} [get_ports RESET]
set_property -dict {PACKAGE_PIN L3 IOSTANDARD LVCMOS18} [get_ports IN]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS18} [get_ports OUT[3]]
set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVCMOS18} [get_ports OUT[2]]
set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVCMOS18} [get_ports OUT[1]]
set_property -dict {PACKAGE_PIN F16 IOSTANDARD LVCMOS18} [get_ports OUT[0]]
set_property -dict {PACKAGE_PIN D20 IOSTANDARD LVCMOS18} [get_ports SEGMENT[0]]
set_property -dict {PACKAGE_PIN C20 IOSTANDARD LVCMOS18} [get_ports SEGMENT[1]]
set_property -dict {PACKAGE_PIN C22 IOSTANDARD LVCMOS18} [get_ports SEGMENT[2]]
set_property -dict {PACKAGE_PIN B22 IOSTANDARD LVCMOS18} [get_ports SEGMENT[3]]
set_property -dict {PACKAGE_PIN B21 IOSTANDARD LVCMOS18} [get_ports SEGMENT[4]]
set_property -dict {PACKAGE_PIN A21 IOSTANDARD LVCMOS18} [get_ports SEGMENT[5]]
set_property -dict {PACKAGE_PIN E22 IOSTANDARD LVCMOS18} [get_ports SEGMENT[6]]
set_property -dict {PACKAGE_PIN E14 IOSTANDARD LVCMOS18} [get_ports DIGIT]