set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets CLK_IBUF]
set_property -dict {PACKAGE_PIN F21 IOSTANDARD LVCMOS18} [get_ports CLK]
set_property -dict {PACKAGE_PIN J4 IOSTANDARD LVCMOS18} [get_ports RESET]
set_property -dict {PACKAGE_PIN L3 IOSTANDARD LVCMOS18} [get_ports X]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS18} [get_ports Q[3]]
set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVCMOS18} [get_ports Q[2]]
set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVCMOS18} [get_ports Q[1]]
set_property -dict {PACKAGE_PIN F16 IOSTANDARD LVCMOS18} [get_ports Q[0]]
set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVCMOS18} [get_ports Z]