set_property -dict {PACKAGE_PIN J4 IOSTANDARD LVCMOS18} [get_ports a1]
set_property -dict {PACKAGE_PIN L3 IOSTANDARD LVCMOS18} [get_ports a2]
set_property -dict {PACKAGE_PIN K3 IOSTANDARD LVCMOS18} [get_ports b1]
set_property -dict {PACKAGE_PIN M2 IOSTANDARD LVCMOS18} [get_ports b2]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS18} [get_ports f1]
set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVCMOS18} [get_ports f2]
set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVCMOS18} [get_ports f3]